### ISSUE TITLE
6.9.9.16 doesn't build

### ISSUE THREAD

**Issue by antonio-rojas** [ImageMagick/ImageMagick#823]
### Description
imagemagick 6.9.9.16 doesn't build on Arch x86_64, GCC 7.2

```
In file included from ./magick/studio.h:170:0,
                 from magick/opencl.c:43:
magick/opencl.c: In function ‘RecordProfileData’:
./magick/method-attribute.h:112:29: error: ‘magick_unused_clEnv’ undeclared (first use in this function); did you mean ‘magick_unused’?
 #  define magick_unused(x)  magick_unused_ ## x __attribute__((unused))
```

**Comment by antonio-rojas** [comment]
Bisected to 5e3d45f4bad0bf836e2218302245dcfb52219ea4

**Comment by dlemstra** [comment]
Thanks for the problem report. We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today. The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
