### ISSUE TITLE
Unable to compile😶

### ISSUE THREAD

**Issue by 311303** [ImageMagick/ImageMagick#1848]
I tried 7.0.9-24 and 7.0.9-26, both of which are errors.
I used it.
`
../configure --prefix=/data/gcc --with-perl=yes --with-gslib=yes --with-autotrace=yes --with-modules=yes --with-tcmalloc=yes --disable-docs && make -j4
`
![7dc2a8d520694c33](https://user-images.githubusercontent.com/41131571/75092901-9d9e6100-55b7-11ea-91a9-b3b17b8720ec.jpg)

Is this a problem with 'AutoTrace' enabled?

**Comment by urban-warrior** [comment]
We tried a build with autotrace 0.31.1 enabled and ImageMagick compiled without complaint.  Not sure why its failing for you.  If you can live without autotrace, do not add --with-autotrace to the ImageMagick configure script command-line.  ImageMagick should then compile.

**Comment by dlemstra** [comment]
It seems that `at_bitmap_type` got renamed to `at_bitmap` (https://github.com/autotrace/autotrace/commit/1a4e3232cd8272c0f69c216aa7b83537bb31008d). This seems to be done after the 0.31.1 but the commit history of this project is not easy to read. This is the current version of autotrace.h: https://github.com/autotrace/autotrace/blob/master/src/autotrace.h. Which version of autotrace are you using @311303? Maybe we should add a version check for this?

**Comment by 311303** [comment]
> It seems that `at_bitmap_type` got renamed to `at_bitmap` ([autotrace/autotrace@1a4e323](https://github.com/autotrace/autotrace/commit/1a4e3232cd8272c0f69c216aa7b83537bb31008d)). This seems to be done after the 0.31.1 but the commit history of this project is not easy to read. This is the current version of autotrace.h: https://github.com/autotrace/autotrace/blob/master/src/autotrace.h. Which version of autotrace are you using @311303? Maybe we should add a version check for this?

I use AutoTrace 0.31.2

I've removed AutoTrace now. It's very smooth to execute `make-j4`. But when I execute `make DESTDIR=/data/test install`, an error is reported
`Q16HDRI.xs:11567:18: error: too few arguments to function 'ColorThresholdImage'`
I found that ColorThresholdImage in MagickCore/threshold.h:49 has four arguments, while PerlMagick/quantum/quantum.xs.in:11567 has only three.

**Comment by urban-warrior** [comment]
Fixed.

**Comment by 311303** [comment]
> Thanks for the problem report. We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today. The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

thanks😁
