### ISSUE TITLE
Cannot build with jpeg-xl v0.2 delegate

### ISSUE THREAD

**Issue by marto55555** [ImageMagick/ImageMagick#3152]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
`make` gives the following error:
<pre>
  CC       coders/MagickCore_libMagickCore_7_Q16HDRI_la-jxl.lo
coders/jxl.c:259:51: error: too many arguments to function call, expected single argument 'dec', have 3 arguments
    decoder_status=JxlDecoderProcessInput(decoder,&p,&input_size);
                   ~~~~~~~~~~~~~~~~~~~~~~         ^~~~~~~~~~~~~~
/usr/local/include/jxl/decode.h:355:1: note: 'JxlDecoderProcessInput' declared here
JXL_EXPORT JxlDecoderStatus JxlDecoderProcessInput(JxlDecoder* dec);
^
/usr/local/include/jxl/jxl_export.h:15:26: note: expanded from macro 'JXL_EXPORT'
#      define JXL_EXPORT __attribute__((visibility("default")))
                         ^
1 error generated.
make[1]: *** [Makefile:10133: coders/MagickCore_libMagickCore_7_Q16HDRI_la-jxl.lo] Error 1
make[1]: Leaving directory '/tmp/ImageMagick-7.0.10-58'
make: *** [Makefile:6120: all] Error 2
</pre>
This seems to be caused from changes introduced ~~in~~ after [jpeg-xl v0.2](https://gitlab.com/wg1/jpeg-xl/-/commit/945ad0ce4262382f850bea3f5cc51ca5cc2a40a2#7c4a11565bd596320dd0be9bd1b451898eea8f4c_360_355).

### Steps to Reproduce
1. Install the latest version of the jpeg-xl delegate library from https://gitlab.com/wg1/jpeg-xl
2. Try to build ImageMagick:
3. `./configure --with-jxl=yes --disable-static`
4. `make`

### System Configuration
<!-- Tell us about the environment where you are experiencing the bug -->

- ImageMagick version: 7.0.10-58
- Environment (Operating system, version and so on): Ubuntu 20.04 from its official Docker image
- Additional information:

<!-- Thanks for reporting the issue to ImageMagick! -->

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by dlemstra** [comment]
I had to revert these changes. It looks like those changes are only made in the main branch and not published in a release yet. Once that new release (probably 0.3) has been released we will make the changes here. They might introduce more breaking changes in the mean time. For now you will need to stick with the 0.2 version of the jpeg-xl library.

**Comment by dlemstra** [comment]
We have updated the coder to use the new API of the 0.3 release.
