### ISSUE TITLE
Build error with libheif 1.18.2

### ISSUE THREAD

**Issue by corentin-soriano** [ImageMagick/ImageMagick#8740]
### ImageMagick version

7.1.2-23

### Operating system

Linux

### Operating system, version and so on

Oracle Linux 8

### Description

This change breaks the build with libheif 1.18 : https://github.com/ImageMagick/ImageMagick/commit/f8d494492562ed22e6a5ab9196ae7c6bb1d2d6ba#diff-cf133db60a54549531dbba5cb2d17dc34f7171cabd115ec7c85c6d3f1e84fb2bL983

Error :
```
[root@549e7b251323 ImageMagick-7.1.2-23]# make
make  all-am
make[1]: Entering directory '/opt/rpm_builder/build/BUILD/ImageMagick-7.1.2-23'
  CC       coders/MagickCore_libMagickCore_7_Q16HDRI_la-heic.lo
coders/heic.c: In function 'ReadHEICImage':
coders/heic.c:987:3: warning: implicit declaration of function 'HEICSecurityLimits' [-Wimplicit-function-declaration]
   HEICSecurityLimits(image_info,heif_context);
   ^~~~~~~~~~~~~~~~~~
  CCLD     MagickCore/libMagickCore-7.Q16HDRI.la
  CCLD     MagickWand/libMagickWand-7.Q16HDRI.la
  CXXLD    utilities/magick
MagickCore/.libs/libMagickCore-7.Q16HDRI.so: undefined reference to `HEICSecurityLimits'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:8256: utilities/magick] Error 1
make[1]: Leaving directory '/opt/rpm_builder/build/BUILD/ImageMagick-7.1.2-23'
make: *** [Makefile:6305: all] Error 2
[root@549e7b251323 ImageMagick-7.1.2-23]# 
```
I tried to revert the line to `#if LIBHEIF_NUMERIC_VERSION >= HEIC_COMPUTE_NUMERIC_VERSION(1,19,0)` and the compilation worked.

### Steps to Reproduce

Install libheif 1.18.2
Build imagemagick 7.1.2-23 with `--with-heic=yes` flag

### Images

No picture at build time!

**Comment by dlemstra** [comment]
Thanks for reporting this. I just pushed a patch that should fix this. Can you confirm this resolves your issue?

**Comment by corentin-soriano** [comment]
It doesn't work:
```
[root@549e7b251323 ImageMagick-7.1.2-23]# pkg-config --modversion libheif
1.18.2
[root@549e7b251323 ImageMagick-7.1.2-23]# make
make  all-am
make[1]: Entering directory '/opt/rpm_builder/build/BUILD/ImageMagick-7.1.2-23'
  CC       coders/MagickCore_libMagickCore_7_Q16HDRI_la-heic.lo
coders/heic.c: In function 'HEICSecurityLimits':
coders/heic.c:161:19: warning: implicit declaration of function 'heif_context_get_security_limits'; did you mean 'heif_context_set_primary_image'? [-Wimplicit-function-declaration]
   security_limits=heif_context_get_security_limits(heif_context);
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                   heif_context_set_primary_image
coders/heic.c:161:18: warning: assignment to 'struct heif_security_limits *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
   security_limits=heif_context_get_security_limits(heif_context);
                  ^
coders/heic.c:165:20: error: dereferencing pointer to incomplete type 'struct heif_security_limits'
     security_limits->max_image_size_pixels=(uint64_t) width_limit*height_limit;
                    ^~
make[1]: *** [Makefile:10368: coders/MagickCore_libMagickCore_7_Q16HDRI_la-heic.lo] Error 1
make[1]: Leaving directory '/opt/rpm_builder/build/BUILD/ImageMagick-7.1.2-23'
make: *** [Makefile:6305: all] Error 
```

Security limits seems to have been added in version [1.19.0](https://github.com/strukturag/libheif/releases/tag/v1.19.0) ([commit](https://github.com/strukturag/libheif/commit/2374ade0a24f107d5de8fb6bd5f9ceef04b6c510))

**Comment by dlemstra** [comment]
I thought I check this and saw that it was introduced in 1.18 but it looks like it was 1.19. I just pushed a patch to fix this. Can you give it another try?

**Comment by corentin-soriano** [comment]
It compiles correctly this time, thank you!
