### ISSUE TITLE
Compilation fails due to ISO C90 violation (mixed declarations and code)

### ISSUE THREAD

**Issue by RiderALT** [ImageMagick/ImageMagick#8156]
### ImageMagick version

7.1.1-41

### Operating system

Linux

### Operating system, version and so on

ALT Linux Sisyphus

### Description

Compilation of software (freeeswitch in this example)  using ImageMagick 7 headers fails when strict ISO C90 compliance (-Wdeclaration-after-statement) is enforced. The issue occurs specifically in quantum.h, where mixed declarations and code are used.

```making all mod_imagick
make[4]: Entering directory '/usr/src/RPM/BUILD/freeswitch-1.10.12/src/mod/formats/mod_imagick'
/bin/sh /usr/src/RPM/BUILD/freeswitch-1.10.12/libtool  --tag=CC   --mode=compile x86_64-alt-linux-gcc -DHAVE_CONFIG_H -I. -I../../../../src/include -I../../../../libs/esl/src/include -I../../../../libs/xmlrpc-c  -I/usr/src/RPM/BUILD/freeswitch-1.10.12/src/include -I/usr/src/RPM/BUILD/freeswitch-1.10.12/src/include -I/usr/src/RPM/BUILD/freeswitch-1.10.12/libs/libteletone/src -fPIC -ffast-math -fvisibility=hidden -DSWITCH_API_VISIBILITY=1 -DCJSON_API_VISIBILITY=1 -DHAVE_VISIBILITY=1  -I/usr/include/uuid -I/usr/src/RPM/BUILD/freeswitch-1.10.12/src/include -I/usr/src/RPM/BUILD/freeswitch-1.10.12/src/include -I/usr/src/RPM/BUILD/freeswitch-1.10.12/libs/libteletone/src -fPIC -ffast-math -Werror -Wno-unused-result -Wno-misleading-indentation -fvisibility=hidden -DSWITCH_API_VISIBILITY=1 -DCJSON_API_VISIBILITY=1 -DHAVE_VISIBILITY=1 -g -ggdb -DHAVE_OPENSSL -Wall -std=c99 -pedantic -Wdeclaration-after-statement -fopenmp -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16 -DMAGICKCORE_CHANNEL_MASK_DEPTH=32 -I/usr/include/ImageMagick-7 -DHAVE_MAGIC7 -pipe -frecord-gcc-switches -Wall -g -O2  -Wno-error=address -std=c99 -c -o mod_imagick_la-mod_imagick.lo `test -f 'mod_imagick.c' || echo './'`mod_imagick.c
libtool: compile:  x86_64-alt-linux-gcc -DHAVE_CONFIG_H -I. -I../../../../src/include -I../../../../libs/esl/src/include -I../../../../libs/xmlrpc-c -I/usr/src/RPM/BUILD/freeswitch-1.10.12/src/include -I/usr/src/RPM/BUILD/freeswitch-1.10.12/src/include -I/usr/src/RPM/BUILD/freeswitch-1.10.12/libs/libteletone/src -fPIC -ffast-math -fvisibility=hidden -DSWITCH_API_VISIBILITY=1 -DCJSON_API_VISIBILITY=1 -DHAVE_VISIBILITY=1 -I/usr/include/uuid -I/usr/src/RPM/BUILD/freeswitch-1.10.12/src/include -I/usr/src/RPM/BUILD/freeswitch-1.10.12/src/include -I/usr/src/RPM/BUILD/freeswitch-1.10.12/libs/libteletone/src -fPIC -ffast-math -Werror -Wno-unused-result -Wno-misleading-indentation -fvisibility=hidden -DSWITCH_API_VISIBILITY=1 -DCJSON_API_VISIBILITY=1 -DHAVE_VISIBILITY=1 -g -ggdb -DHAVE_OPENSSL -Wall -std=c99 -pedantic -Wdeclaration-after-statement -fopenmp -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16 -DMAGICKCORE_CHANNEL_MASK_DEPTH=32 -I/usr/include/ImageMagick-7 -DHAVE_MAGIC7 -pipe -frecord-gcc-switches -Wall -g -O2 -Wno-error=address -std=c99 -c mod_imagick.c  -fPIC -DPIC -o .libs/mod_imagick_la-mod_imagick.o
In file included from /usr/include/ImageMagick-7/MagickCore/image.h:124,
                 from /usr/include/ImageMagick-7/MagickCore/draw.h:22,
                 from /usr/include/ImageMagick-7/MagickCore/annotate.h:21,
                 from /usr/include/ImageMagick-7/MagickCore/MagickCore.h:80,
                 from mod_imagick.c:53:
/usr/include/ImageMagick-7/MagickCore/quantum.h: In function 'ScaleQuantumToChar':
/usr/include/ImageMagick-7/MagickCore/quantum.h:120:3: error: ISO C90 forbids mixed declarations and code [-Werror=declaration-after-statement]
  120 |   const Quantum scaled = quantum/257.0f;
      |   ^~~~~
cc1: all warnings being treated as errors
make[4]: *** [Makefile:746: mod_imagick_la-mod_imagick.lo] Error 1
make[4]: Leaving directory '/usr/src/RPM/BUILD/freeswitch-1.10.12/src/mod/formats/mod_imagick'
make[3]: *** [Makefile:731: mod_imagick-all] Error 1
make[3]: Leaving directory '/usr/src/RPM/BUILD/freeswitch-1.10.12/src/mod'
make[2]: *** [Makefile:632: all-recursive] Error 1
make[2]: Leaving directory '/usr/src/RPM/BUILD/freeswitch-1.10.12/src'
make[1]: *** [Makefile:3771: all-recursive] Error 1
make[1]: Leaving directory '/usr/src/RPM/BUILD/freeswitch-1.10.12'
make: *** [Makefile:1444: all] Error 2
make: Leaving directory '/usr/src/RPM/BUILD/freeswitch-1.10.12'
```

This issue is introduced in commit fb883b589c037504717caf632044521d80865149

### Steps to Reproduce

Build freeswitch with ImageMagick-7.1.1-41 and gcc 14.2.1

### Images

Image is not needed.

**Comment by dlemstra** [comment]
It's fine that they/you enable C90 but we don't build our project with those settings. Also not sure if we should. Do you get the same error with C99?

**Comment by RiderALT** [comment]
Yes, the same error occurs with -std=c99.

**Comment by RiderALT** [comment]
freeswitch uses -Wdeclaration-after-statement for supported compilers  starting with version 1.0.5 (released in 2010)

**Comment by dlemstra** [comment]
I just pushed a patch that we also include `-Wdeclaration-after-statement` in our commit builds. Thanks for bringing this to our attention.
