### ISSUE TITLE
7.1.0-27 fails to build with `--with-jxl`

### ISSUE THREAD

**Issue by erictapen** [ImageMagick/ImageMagick#4936]
### ImageMagick version

7.1.0-27

### Operating system

Linux

### Operating system, version and so on

Nixpkgs unstable

### Description

When trying to package 7.1.0-27 for [Nixpkgs](https://github.com/NixOS/nixpkgs/), I'm seeing a build error related to the `--with-jxl` configure flag:

```
...
  CXX      Magick++/lib/libMagick___7_Q16HDRI_la-BlobRef.lo
  CXX      Magick++/lib/libMagick___7_Q16HDRI_la-CoderInfo.lo
  CXX      Magick++/lib/libMagick___7_Q16HDRI_la-Color.lo
  CXX      Magick++/lib/libMagick___7_Q16HDRI_la-Drawable.lo
  CXX      Magick++/lib/libMagick___7_Q16HDRI_la-Exception.lo
  CXX      Magick++/lib/libMagick___7_Q16HDRI_la-Functions.lo
  CXX      Magick++/lib/libMagick___7_Q16HDRI_la-Geometry.lo
  CXX      Magick++/lib/libMagick___7_Q16HDRI_la-Image.lo
  CXX      Magick++/lib/libMagick___7_Q16HDRI_la-ImageRef.lo
  CXX      Magick++/lib/libMagick___7_Q16HDRI_la-Montage.lo
  CXX      Magick++/lib/libMagick___7_Q16HDRI_la-Options.lo
  CXX      Magick++/lib/libMagick___7_Q16HDRI_la-Pixels.lo
  CXX      Magick++/lib/libMagick___7_Q16HDRI_la-ResourceLimits.lo
  CXX      Magick++/lib/libMagick___7_Q16HDRI_la-SecurityPolicy.lo
  CXX      Magick++/lib/libMagick___7_Q16HDRI_la-Statistic.lo
  CXX      Magick++/lib/libMagick___7_Q16HDRI_la-STL.lo
  CXX      Magick++/lib/libMagick___7_Q16HDRI_la-Thread.lo
  CXX      Magick++/lib/libMagick___7_Q16HDRI_la-TypeMetric.lo
  CCLD     MagickCore/libMagickCore-7.Q16HDRI.la
/nix/store/sga0l55gm9nlwglk79lmihwb2bpv597j-binutils-2.35.2/bin/ld: coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-jxl.o: in function `RegisterJXLImage':
/tmp/nix-build-imagemagick-7.1.0-26.drv-0/ImageMagick/coders/jxl.c:462: multiple definition of `RegisterJXLImage'; coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-jxl.o:/tmp/nix-build-imagemagick-7.1.0-26.drv-0/ImageMagick/coders/jxl.c:462: first defined here
/nix/store/sga0l55gm9nlwglk79lmihwb2bpv597j-binutils-2.35.2/bin/ld: coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-jxl.o: in function `UnregisterJXLImage':
/tmp/nix-build-imagemagick-7.1.0-26.drv-0/ImageMagick/coders/jxl.c:493: multiple definition of `UnregisterJXLImage'; coders/.libs/MagickCore_libMagickCore_7_Q16HDRI_la-jxl.o:/tmp/nix-build-imagemagick-7.1.0-26.drv-0/ImageMagick/coders/jxl.c:493: first defined here
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:7131: MagickCore/libMagickCore-7.Q16HDRI.la] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/tmp/nix-build-imagemagick-7.1.0-26.drv-0/ImageMagick'
make: *** [Makefile:6166: all] Error 2
```

`git bisect` tells me that the regression was introduced with 18f7a0afba8374f6b52053a383101d36aef0dab6.

### Steps to Reproduce

I'm building with Nix, so you'd need to checkout https://github.com/erictapen/nixpkgs/tree/imagemagick and run `nix-build -A imagemagick` to reproduce the failure. On `x86_64-linux` this would use the `--with-jxl` configure flag.

**Comment by urban-warrior** [comment]
Is this a fresh install?  If not, can you try a `make distclean; ./configure --with-jxl; make`.  This is likely a build issue rather than an issue with ImageMagick-- or at least for our team, JXL works fine under CentOS, Fedora, and Windows.

**Comment by bobvanmanen** [comment]
This might be a problem specific to `clang`.

I believe the problem is that in `Makefile.in`, `jnx.lo` is added explicitly to `am__objects_19`:

```
	coders/MagickCore_libMagickCore_@MAGICK_MAJOR_VERSION@_@MAGICK_ABI_SUFFIX@_la-jnx.lo \
```

However, `am__objects_13` is also added to `am__objects_19` which is defined as:

```
@JXL_DELEGATE_TRUE@am__objects_13 = coders/MagickCore_libMagickCore_@MAGICK_MAJOR_VERSION@_@MAGICK_ABI_SUFFIX@_la-jxl.lo
```

The result is that `jxl.lo` is added twice causing the multiple definition error. Removing the explicit reference and keeping the reference to `am_objects_13` fixes the problem.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.
