### ISSUE TITLE
[7.0.9-16] Broken build with old librsvg

### ISSUE THREAD

**Issue by remicollet** [ImageMagick/ImageMagick#1830]
On RHEL 6 with version librsvg 2.26

```
coders/svg.c: In function 'ReadSVGImage':
coders/svg.c:3317: warning: implicit declaration of function 'rsvg_handle_new_with_flags'
coders/svg.c:3317: error: 'RSVG_HANDLE_FLAG_UNLIMITED' undeclared (first use in this function)
coders/svg.c:3317: error: (Each undeclared identifier is reported only once
coders/svg.c:3317: error: for each function it appears in.)
```

7.0.9-14 build was OK, and  configure.ac check fir

`  PKG_CHECK_MODULES(RSVG,[librsvg-2.0 >= 2.9.0], have_rsvg=yes, have_rsvg=no)`

**Comment by remicollet** [comment]
Build on RHEL-7 with 2.40 is OK.

**Comment by dlemstra** [comment]
Thanks for the problem report. We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today. The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
