### ISSUE TITLE
Build error with libheif 1.22.0

### ISSUE THREAD

**Issue by fundawang** [ImageMagick/ImageMagick#8747]
### ImageMagick version

7.1.2-23

### Operating system

Linux

### Operating system, version and so on

openEuler

### Description

```
2026-05-20 08:02:56 make[1]: Leaving directory '/home/lkp/rpmbuild/BUILD/ImageMagick-7.1.2-23'
2026-05-20 08:02:56 In file included from coders/heic.c:84:
2026-05-20 08:02:56 /usr/include/libheif/heif_properties.h:338:56: error: unknown type name 'heif_bad_pixel'
2026-05-20 08:02:56   338 |                                                  const heif_bad_pixel* bad_pixels);
2026-05-20 08:02:56       |                                                        ^~~~~~~~~~~~~~
2026-05-20 08:02:56 make[1]: *** [Makefile:10921: coders/heic_la-heic.lo] Error 1
2026-05-20 08:02:56 make[1]: *** Waiting for unfinished jobs....
```

### Steps to Reproduce

Compile with libheif 1.22.0

### Images

none

**Comment by bkuhls** [comment]
Please test this commit for libheif to fix the problem: https://github.com/strukturag/libheif/commit/ef124f9988e57a06ad6d102c236d2bb4b82aef5d

**Comment by dlemstra** [comment]
Closing this because this is an issue in libheif and not ImageMagick.
